blog/urls.py
from django.conf.urls import url
from . import views
urlpatterns = [
    url(r'^$',views.Index.as_view()),
    url(r'^login/$',views.Login.as_view()),
    url(r'^logout/$',views.Logout.as_view()),
    url(r'^register/$',views.Register.as_view()),

    url(r'^site/(?P<username>\w+)/(?P<condition>category|tag|date)/(?P<param>.*)/$',views.Homesite.as_view()),
    url(r'^site/(?P<username>\w+)/$',views.Homesite.as_view()),
    url(r'^site/(?P<username>\w+)/article/(?P<article_id>\d+)/$',views.Article_detail.as_view()),
    url(r'^edit/(?P<article_id>\d+)/$',views.Editor.as_view()),
]

cnblog/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from blog import views
from django.views.static import serve
from cnblog import settings
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',views.Index.as_view()),
    url(r'^up_down/$',views.Up_down.as_view()),
    url(r'^up_load/$',views.Up_load.as_view()),
    url(r'^comment/$',views.Sub_comment.as_view()),
    url(r'^backend/$',views.Backend.as_view()),
    url(r'^addarticle/$',views.Addarticle.as_view()),
    url(r'^cnblog.com/', include('blog.urls')),
    url(r'^article/', include('blog.urls')),
    url(r'^validcode/',views.get_valid_img),

    # media 配置
    url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
]

blog/forms.py
from django import forms
from django.forms import widgets
from .models import *
from django.core.exceptions import NON_FIELD_ERRORS, ValidationError


class RegisterForm(forms.Form):
    user=forms.CharField(min_length=5,error_messages={"required":"该字段不能为空","min_length":"最短为5个字符"},
                         widget=widgets.TextInput(attrs={"class":"form-control","placeholder":"用户名"})
                         )
    pwd=forms.CharField(min_length=8,error_messages={"required":"该字段不能为空","min_length":"最短为个8字符"},
                        widget=widgets.PasswordInput(attrs={"class":"form-control","placeholder":"密码"})
                        )
    repeat_pwd=forms.CharField(min_length=8,error_messages={"required":"该字段不能为空","min_length":"最短为个8字符"},
                        widget=widgets.PasswordInput(attrs={"class":"form-control","placeholder":"确认密码"})
                               )
    email=forms.EmailField(error_messages={"required":"该字段不能为空","invalid":"格式错误"},
                           widget=widgets.EmailInput(attrs={"class":"form-control","placeholder":"邮箱"})
                           )

    def clean_user(self):
        val=self.cleaned_data.get("user")
        if not UserInfo.objects.filter(username=val):
            return val
        else:
            raise ValidationError("用户已存在！")

    def clean(self):
        pwd=self.cleaned_data.get("pwd")
        repeat_pwd=self.cleaned_data.get("repeat_pwd")
        if pwd and repeat_pwd:
            if pwd==repeat_pwd:
                return self.cleaned_data
            else:
                raise ValidationError("两次密码不一致")
        else:
            return self.cleaned_data

templates/addarticle.html
{% extends "backendbase.html" %}
{% block content %}
    <h3 class="page-header">添加文章</h3>
    <form action="" method="post">
        {% csrf_token %}
        <div class="input-group input-group col-md-8">
            <span class="input-group-addon" id="sizing-addon1">文章标题</span>
            <input type="text" class="form-control" placeholder="标题" aria-describedby="sizing-addon1" name="title">
        </div>
        <textarea id="editor_id" name="content" style="width:800px;height:400px;">
            </textarea>
        <button class="button btn-success" type="submit">提交</button>
    </form>
    <script charset="utf-8" src="/static/kindeditor/kindeditor-all.js"></script>
    <script>
        KindEditor.ready(function (K) {
            window.editor = K.create('#editor_id', {
                width: 600,
                height: 600,
                resizeType: 0,
                uploadJson: "/up_load/",
                extraFileUploadParams: {
                    csrfmiddlewaretoken: $("[name='csrfmiddlewaretoken']").val()
                },
                filePostName: "upload_img"
            });
        });
    </script>
{% endblock %}

templates/article.html
{% extends "base.html" %}
{% block content %}
    {{ article_obj.content|safe }}
    <div id="div_digg" class="clearfix">
        <div class="diggit up_down">
            <span class="diggnum" id="digg_count">{{ article_obj.up_count }}</span>
        </div>
        <div class="buryit up_down">
            <span class="burynum" id="bury_count">{{ article_obj.down_count }}</span>
        </div>
        <div class="clear"></div>
        <div class="diggword" id="digg_tips">
        </div>
        {% csrf_token %}
    </div>
    <div class="clear"></div>
    <div id="comment">
        <hr>
        {% for comment in comment_list %}
            {% if comment.parent_comment.id %}

            {% endif %}
            <div>
                <div class="info">
                    <span style="color: #2b669a">#{{ forloop.counter }}楼</span> &nbsp;
                    <span>{{ comment.create_time|date:'Y-m-d H:i:s' }}</span> &nbsp;
                    <span style="color: #2b669a">{{ comment.user.username }}</span>
                    <a href="javascript:void(0)" class="pull-right sub_comment" comment_id="{{ comment.pk }}"
                       username="{{ comment.user.username }}">回复</a>
                </div>
                {% if comment.parent_comment.pk %}
                    <div class="">
                        <p style="color: #888;">{{ comment.parent_comment.content }}</p>
                    </div>
                    <div class="well">
                        <span class="small pull-right" style="color: #888;">{{ comment.content }} By {{ comment.user.username }}</span>
                    </div>
                {% else %}
                    <div>
                        <span class="" style="color: #888;">{{ comment.content }}</span>
                    </div>
                {% endif %}
                <hr>
            </div>
        {% endfor %}

    </div>

    <div class="commentform clearfix">
        <div id="comment_form_container" class="clearfix">
            <script type="text/javascript" src="//mention.cnblogs.com/bundles/mention.js?id=20160615"></script>
            <div id="commentform_title">发表评论</div>
            <span id="tip_comment" style="color:Red"></span>
            <p>
                昵称：<input type="text" id="tbCommentAuthor" class="author" disabled="disabled" size="50"
                          value="{{ user.username }}">
            </p>
            <div class="commentbox_main">
                <div class="commentbox_title">
                    <div class="commentbox_title_left">评论内容：</div>
                </div>
                <div class="clear"></div>
                <textarea id="tbCommentBody" class="comment_textarea"></textarea>
            </div>
            <p id="commentbox_opt">
                <input id="btn_comment_submit" type="button" class="comment_btn" value="提交评论">
            </p>
            <div id="tip_comment2" style="color:Red"></div>
            <div style="display:none">
                <span id="comment_edit_id"></span><span id="span_parentcomment_id"></span>
                <span id="span_parent_id"></span>
                <span id="span_comment_replyto"></span>
                <span id="span_comment_posted"></span>
            </div>
        </div>
    </div>
    <script>
        /*点赞与踩灭功能*/
        $(".up_down").click(function () {
            {#当点击的标签有diggit类表明点击的是点赞标签，则返回为true，否则为false#}
            var is_up = $(this).hasClass("diggit");
            var _this = $(this).children("span");
            $.ajax({
                url: "/up_down/",
                type: "post",
                data: {
                    csrfmiddlewaretoken: $("[name='csrfmiddlewaretoken']").val(),
                    article_id:{{ article_id }},
                    is_up: is_up,
                },
                success: function (data) {
                    if (data["status"]) {
                        _this.text(parseInt(_this.text()) + 1);
                    } else {
                        $("#digg_tips").text(data["msg"]);
                    }
                }
            });
            setTimeout(function () {
                $("#digg_tips").text("");
            }, 1000);
        });
        /*评论功能*/
        /*判读根评论与子评的依据是：
        *   在默认情况下parent_id为空，那么后端接收到的parent_id就也是为空的，当点击回复按钮之后，会立刻更改全局变量parent_id 的值。
        * */
        var parent_id = "";
        $("#btn_comment_submit").click(function () {
            var content = $("#tbCommentBody").val();
            $.ajax({
                url: "/comment/",
                type: 'post',
                data: {
                    csrfmiddlewaretoken: $("[name='csrfmiddlewaretoken']").val(),
                    /*后台只要是传入模板中的变量在JS中同样可以调用*/
                    article_id:{{ article_id }},
                    comment: content,
                    parent_id: parent_id,
                },
                success: function (data) {
                    var div1 = document.createElement("div");
                    div1.style.border = '1px solid #ddd';
                    var p1 = document.createElement("b");
                    p1.style.color = "#399ab2";
                    var p2 = document.createElement("p");
                    p1.innerText = "{{ user.username }}:";
                    p2.innerText = content;
                    div1.appendChild(p1);
                    div1.appendChild(p2);
                    $("#comment").append(div1);
                }
            });
        });
        /*回复自评论功能*/
        $(".sub_comment").click(function () {
            /*点击回复之后将光标获取到textarea*/
            $("#tbCommentBody").focus();
            /*更改全局parent_id*/
            var username = $(this).attr("username");
            var get_parent_id = $(this).attr("comment_id");
            parent_id = get_parent_id;
            $("#tbCommentBody").text("@" + username + "\n");
        });
    </script>
{% endblock %}

templates/backend.html
{% extends "backendbase.html" %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>首页</title>
    <link rel="stylesheet" href="/static/bootstrap/css/bootstrap.css">
    <script src="/static/js/jquery.js"></script>
    <script src="/static/bootstrap/js/bootstrap.js"></script>
    <style>
        .title {
            line-height: 50px;
            font-weight: lighter;
            font-size: 18px;
            margin: 0 auto;
        }

        #div_digg {
            float: right;
            margin-bottom: 10px;
            margin-right: 30px;
            font-size: 12px;
            width: 125px;
            text-align: center;
            margin-top: 10px;
        }

        .diggit {
            float: left;
            width: 46px;
            height: 52px;
            background: url(/static/pic/upup.gif) no-repeat;
            text-align: center;
            cursor: pointer;
            margin-top: 2px;
            padding-top: 5px;
        }

        .buryit {
            float: right;
            margin-left: 20px;
            width: 46px;
            height: 52px;
            background: url(/static/pic/downdown.gif) no-repeat;
            text-align: center;
            cursor: pointer;
            margin-top: 2px;
            padding-top: 5px;
        }

        .diggword {
            margin-top: 5px;
            margin-left: 0;
            font-size: 12px;
            color: red;
        }

        .clear {
            clear: both;
        }

        #commentform_title {
            background-image: url(/static/pic/icon_addcomment.gif);
            background-repeat: no-repeat;
            padding: 0 0 0 25px;
            margin-bottom: 10px;
        }

        div.commentform p {
            margin-top: 10px;
            line-height: 20px;
        }

        div.commentform textarea.comment_textarea {
            line-height: 1.6;
        }

        div.commentform textarea {
            width: 450px;
            height: 300px;
            font-size: 13px;
            border: 1px solid #ccc;
            font-family: 'PingFang SC', 'Helvetica Neue', 'Helvetica', 'Arial', sans-serif;
        }

        div.commentform input.author {
            background-position: 3px -3px;
        }

        div.commentform input.author, div.commentform input.email, div.commentform input.url {
            background-image: url(/static/pic/icon_form.gif);
            background-repeat: no-repeat;
            border: 1px solid #ccc;
            padding: 4px 4px 4px 30px;
            width: 300px;
            font-size: 13px;
        }
    </style>
</head>
<body>
<nav class="navbar navbar-default navbar-static-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <p class="title">{{ user.blog.title }}</p>
        </div>
                <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav" style="margin-left: 5px">
                <li class="active"><a href="/cnblog.com/">首页</a></li>
                <li class=""><a href="/backend/">管理</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if request.user.username %}
                    <li><a href="../navbar/">{{ request.user.username }}</a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                           aria-expanded="false">个人中心 <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="#">修改用户信息</a></li>
                            <li><a href="#">修改密码</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="#">注销</a></li>
                        </ul>
                    </li>
                {% else %}
                    <li><a href="">注册</a></li>
                    <li><a href="">登录</a></li>
                {% endif %}

            </ul>
        </div><!--/.nav-collapse -->
    </div>
</nav>
<div class="container-fluid">
    <div class="col-md-2">
        {% load mytags %}
        {% left user %}
    </div>
    <div class="col-md-8">
        {% block content %}
            {% for article in article_list %}
                <div>
                    <div class="title">
                        <h5><a href="article/{{ article.pk }}/">{{ article.title }}</a></h5>
                    </div>
                    <div class="desc small">
                        <span class="media-left">{{ article.desc }}</span>
                    </div>
                    <div class="info small pull-right">
                        <span>{{ article.user.username }}</span> <span>发布于</span> &nbsp;
                        <span>{{ article.create_time|date:"Y-m-d H:i:s" }} </span>
                        &nbsp;
                        <span class="glyphicon glyphicon-thumbs-up"></span> 点赞数({{ article.up_count }})
                        &nbsp;
                        <span class="glyphicon glyphicon-pencil"></span> 评论数({{ article.comment_count }})
                    </div>
                </div>
                <hr>
            {% endfor %}
        {% endblock %}
    </div>
</div>
</body>
</html>

templates/editarticle.html
{% extends "backendbase.html" %}
{% block content %}
    <h3 class="page-header">编辑文章</h3>
    <form action="" method="post">
        <div class="input-group input-group col-md-8">
            <span class="input-group-addon" id="sizing-addon1">文章标题</span>
            <input type="text" class="form-control" placeholder="标题" aria-describedby="sizing-addon1" name="title" value="{{ article_obj.title }}">
        </div>
        <textarea id="editor_id" name="content" style="width:800px;height:400px;">
                {{ article_obj.content }}
            </textarea>
        <button class="button btn-success btn-primary" type="submit">提交</button>
    </form>
    <script charset="utf-8" src="/static/kindeditor/kindeditor-all.js"></script>
    <script>
        KindEditor.ready(function (K) {
            window.editor = K.create('#editor_id');
        });
    </script>
{% endblock %}

templates/homesite.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>首页</title>
    <link rel="stylesheet" href="/static/bootstrap/css/bootstrap.css">
    <script src="/static/js/jquery.js"></script>
    <script src="/static/bootstrap/js/bootstrap.js"></script>
    <style>
        .title {
            line-height: 50px;
            font-weight: lighter;
            font-size: 18px;
            margin: 0 auto;
        }
    </style>
</head>
<body>
<nav class="navbar navbar-default navbar-static-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <p class="title">{{ user.blog.title }}</p>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav" style="margin-left: 5px">
                <li class="active"><a href="/cnblog.com/">首页</a></li>
                <li class=""><a href="/backend/">管理</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if request.user.username %}
                    <li><a href="../navbar/">{{ request.user.username }}</a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                           aria-expanded="false">个人中心 <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="#">修改用户信息</a></li>
                            <li><a href="#">修改密码</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="#">注销</a></li>
                        </ul>
                    </li>
                {% else %}
                    <li><a href="">注册</a></li>
                    <li><a href="">登录</a></li>
                {% endif %}

            </ul>
        </div><!--/.nav-collapse -->
    </div>
</nav>
<div class="container-fluid">
    <div class="col-md-2">
        {% load mytags %}
        {% left user %}
    </div>
    <div class="col-md-8">
        {% for article in article_list %}
            <div>
                <div class="title">
                    <h5><a href="/cnblog.com/site/{{ username }}/article/{{ article.pk }}/">{{ article.title }}</a></h5>
                </div>
                <div class="desc small">
                    <span class="media-left">{{ article.desc }}</span>
                </div>
                <div class="info small pull-right">
                    <span>{{ article.user.username }}</span> <span>发布于</span> &nbsp;
                    <span>{{ article.create_time|date:"Y-m-d H:i:s" }} </span>
                    &nbsp;
                    <span class="glyphicon glyphicon-thumbs-up"></span> 点赞数({{ article.up_count }})
                    &nbsp;
                    <span class="glyphicon glyphicon-pencil"></span> 评论数({{ article.comment_count }})
                </div>
            </div>
            <hr>
        {% endfor %}
    </div>
</div>
</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>首页</title>
    <link rel="stylesheet" href="/static/bootstrap/css/bootstrap.css">
    <script src="/static/js/jquery.js"></script>
    <script src="/static/bootstrap/js/bootstrap.js"></script>
</head>
<body>
<nav class="navbar navbar-default navbar-static-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#" style="margin-top: -13px"><img src="/static/pic/logo_small.gif" alt=""
                                                                            height="50"></a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav" style="margin-left: 5px">
                <li class="active"><a href="#">首页</a></li>
                <li><a href="/backend/">管理</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if request.user.username %}
                    <li><a href="../navbar/">{{ request.user.username }}</a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                           aria-expanded="false">个人中心 <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="#">修改用户信息</a></li>
                            <li><a href="#">修改密码</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="/cnblog.com/logout/">注销</a></li>
                        </ul>
                    </li>
                {% else %}
                    <li><a href="/cnblog.com/register/">注册</a></li>
                    <li><a href="/cnblog.com/login/">登录</a></li>
                {% endif %}
            </ul>
        </div><!--/.nav-collapse -->
    </div>
</nav>
<div class="container-fluid">
    <div class="col-md-2">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title">Panel title</h3>
            </div>
            <div class="panel-body">
                Panel content
            </div>
        </div>
        <div class="panel panel-success">
            <div class="panel-heading">
                <h3 class="panel-title">Panel title</h3>
            </div>
            <div class="panel-body">
                Panel content
            </div>
        </div>
        <div class="panel panel-danger">
            <div class="panel-heading">
                <h3 class="panel-title">Panel title</h3>
            </div>
            <div class="panel-body">
                Panel content
            </div>
        </div>
    </div>
    <div class="col-md-8">
        {% for article in article_list %}
            <div>
                <div class="title">
                    <h5><a href="site/{{ article.user.username }}/article/{{ article.pk }}/">{{ article.title }}</a></h5>
                </div>
                <div class="desc small">
                    <a href="site/{{ article.user.username}}/" class="media-left"><img src="/static/pic/timg.jpg" alt="" height="53px" width="53px"></a>
                    <span class="media-right">{{ article.desc }}</span>
                </div>
                <div class="info small">
                    <span>{{ article.user.username }}</span> <span>发布于</span> &nbsp; <span>{{ article.create_time|date:"Y-m-d H:i:s" }} </span>
                    &nbsp;
                    <span class="glyphicon glyphicon-thumbs-up"></span> 点赞数({{ article.up_count }})
                    &nbsp;
                    <span class="glyphicon glyphicon-pencil"></span> 评论数({{ article.comment_count }})
                </div>
            </div>
            <hr>
        {% endfor %}

    </div>
    <div class="col-md-2">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title">Panel title</h3>
            </div>
            <div class="panel-body">
                Panel content
            </div>
        </div>
        <div class="panel panel-success">
            <div class="panel-heading">
                <h3 class="panel-title">Panel title</h3>
            </div>
            <div class="panel-body">
                Panel content
            </div>
        </div>
        <div class="panel panel-danger">
            <div class="panel-heading">
                <h3 class="panel-title">Panel title</h3>
            </div>
            <div class="panel-body">
                Panel content
            </div>
        </div>
    </div>
</div>
</body>
</html>

templates/left.html
<div class="panel panel-primary">
    <div class="panel-heading">
        <h3 class="panel-title">文章分类</h3>
    </div>
    <div class="panel-body">
        {% for category in category_list %}
            <p>
                <a href="/cnblog.com/site/{{ username }}/category/{{ category.title }}/">{{ category.title }}({{ category.c }})</a>
            </p>
        {% endfor %}

    </div>
</div>
<div class="panel panel-success">
    <div class="panel-heading">
        <h3 class="panel-title">我的标签</h3>
    </div>
    <div class="panel-body">
        {% for tag in tag_list %}
            <p><a href="">{{ tag.title }}({{ tag.c }})</a></p>
        {% endfor %}
    </div>
</div>
<div class="panel panel-danger">
    <div class="panel-heading">
        <h3 class="panel-title">日期归档</h3>
    </div>
    <div class="panel-body">
        {% for date in date_list %}
            <p><a href="/cnblog.com/site/{{ username }}/date/{{ date.0 }}/">{{ date.0 }}({{ date.1 }})</a></p>
        {% endfor %}
    </div>
</div>

templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Title</title>
    <link rel="stylesheet" href="/static/bootstrap/css/bootstrap.css">
    <script src="/static/js/jquery.js"></script>
</head>
<body>
<div class="panel panel-info">
    <div class="panel-heading">
        <h4>欢迎注册</h4>
    </div>
    <div class="panel-body">
        <div class="container">
            <div class="row">
                <div class="col-md-6 col-md-offset-3">
                    <form>
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="id_user">用户名</label>
                            {{ register_form.user }}
                            <span class="pull-right"></span>
                        </div>
                        <div class="form-group">
                            <label for="id_pwd">密码</label>
                            {{ register_form.pwd }}
                            <span class="pull-right"></span>
                        </div>
                        <div class="form-group">
                            <label for="id_repeat_pwd">确认密码</label>
                            {{ register_form.repeat_pwd }}
                            <span class="pull-right"></span>
                        </div>
                        <div class="form-group">
                            <label for="id_email">邮箱</label>
                            {{ register_form.email }}
                            <span class="pull-right"></span>
                        </div>

                        <div class="form-group">

                            <label for="avatar">
                                头像
                                <img id="avatar_img" src="/static/pic/default.png" alt="" width="60" height="60">
                            </label>&nbsp;&nbsp;

                            <input type="file" style="display: none;" id="avatar">
                        </div>

                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="valid_code">验证码</label>
                                    <input type="text" class="form-control" id="valid_code" placeholder="验证码">
                                </div>
                            </div>
                            <div class="col-md-6">
                                <img id="valid_img" width="260" height="60" src="/validcode/" alt="">
                            </div>
                        </div>

                        <input type="button" value="注册" class="btn btn-warning  btn-block reg_btn"> <span
                            class="error"></span>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>


<script>
    // 头像预览功能

    $("#avatar").change(function () {
        var choose_file = $(this)[0].files[0];
        var reader = new FileReader();
        reader.readAsDataURL(choose_file);
        reader.onload = function () {
            $("#avatar_img").attr("src", this.result)
        }
    });


    // ajax提交数据
    $(".reg_btn").click(function () {
        var formdata = new FormData();
        formdata.append("user", $("#id_user").val());
        formdata.append("pwd", $("#id_pwd").val());
        formdata.append("repeat_pwd", $("#id_repeat_pwd").val());
        formdata.append("email", $("#id_email").val());
        formdata.append("avatar", $("#avatar")[0].files[0]);
        formdata.append("csrfmiddlewaretoken", $("[name='csrfmiddlewaretoken']").val());

        $.ajax({
            url: "",
            type: "post",
            data: formdata,
            contentType: false,
            processData: false,
            success: function (data) {
                console.log(data);
                var data = JSON.parse(data);
                if (data.user) {
                    location.href = "/cnblog.com/login/"
                }
                else {
                    // 清空上次错误信息
                    $("form span").html("");
                    $(".form-group").removeClass("has-error");

                    // 显示当前错误信息
                    $.each(data.error_msg, function (field, error_info) {
                        console.log(field, error_info[0]);
                        $("#id_" + field).parent().addClass("has-error");
                        $("#id_" + field).next().html(error_info[0]).css("color", "red");
                        // 判断全局错误
                        if (field == "__all__") {
                            $("#id_repeat_pwd").next().html(error_info[0]).css("color", "red");
                            $("#id_repeat_pwd").parent().addClass("has-error");
                        }
                    });


                }
            }
        })

    })


</script>
</body>
</html>